import type {
  DocumentTemplateDefinition,
} from './document-template.types.js';

export const DOCUMENT_TEMPLATE_REGISTRY: DocumentTemplateDefinition[] = [
  {
    code: 'evaluation_module_report',
    name: 'Informe de evaluación de módulo',
    description:
      'Plantilla base para generar un informe de evaluación de un módulo profesional en un periodo de evaluación concreto, separando calificaciones numéricas de estados no evaluables.',
    category: 'evaluation',
    scope: ['module'],
    outputFormats: ['docx', 'pdf', 'xlsx'],
    requiredPermission: 'evaluations.statistics.view',
    requiredInputs: [
      {
        key: 'evaluationId',
        label: 'Evaluación',
        required: true,
        description: 'Selecciona la evaluación. La evaluación ya determina el curso académico y el centro.',
      },
      {
        key: 'moduleId',
        label: 'Módulo',
        required: true,
        description: 'Selecciona el módulo profesional. El módulo ya determina el ciclo y el nivel.',
      },
    ],
    variables: [
      {
        key: 'evaluation.name',
        label: 'Evaluación',
        type: 'string',
        required: true,
        description: 'Nombre del periodo de evaluación.',
        example: 'Evaluación Final',
      },
      {
        key: 'module.name',
        label: 'Módulo',
        type: 'string',
        required: true,
        description: 'Nombre del módulo profesional.',
        example: '0483 · Bases de Datos',
      },
      {
        key: 'stats.enrolled',
        label: 'Matriculados',
        type: 'number',
        required: true,
        description: 'Número de matrículas activas en el contexto del informe.',
      },
      {
        key: 'stats.evaluated',
        label: 'Evaluados',
        type: 'number',
        required: true,
        description: 'Número de alumnos con calificación numérica válida.',
      },
      {
        key: 'stats.passed',
        label: 'Aprobados',
        type: 'number',
        required: true,
        description: 'Número de alumnos aprobados.',
      },
      {
        key: 'stats.failed',
        label: 'Suspensos',
        type: 'number',
        required: true,
        description: 'Número de alumnos suspensos.',
      },
      {
        key: 'stats.notEvaluated',
        label: 'No evaluados',
        type: 'number',
        required: true,
        description: 'Número de alumnos con estados no numéricos.',
      },
      {
        key: 'stats.successRate',
        label: 'Tasa de éxito',
        type: 'number',
        required: true,
        description: 'Porcentaje de aprobados sobre evaluados.',
      },
      {
        key: 'stats.performanceRate',
        label: 'Tasa de rendimiento',
        type: 'number',
        required: true,
        description: 'Porcentaje de aprobados sobre matriculados.',
      },
    ],
    sections: [
      {
        key: 'cover',
        title: 'Portada',
        order: 1,
        required: true,
        description: 'Identificación de la evaluación, módulo y fecha de generación.',
        variables: ['evaluation.name', 'module.name'],
      },
      {
        key: 'summary',
        title: 'Resumen ejecutivo',
        order: 2,
        required: true,
        description: 'Síntesis de resultados y advertencias sobre estados no evaluables.',
        variables: ['stats.enrolled', 'stats.evaluated', 'stats.successRate', 'stats.performanceRate'],
      },
      {
        key: 'results',
        title: 'Resultados académicos',
        order: 3,
        required: true,
        description: 'Detalle de aprobados, suspensos, no evaluados y distribución de calificaciones.',
        variables: ['stats.passed', 'stats.failed', 'stats.notEvaluated'],
      },
      {
        key: 'observations',
        title: 'Observaciones',
        order: 4,
        required: false,
        description: 'Comentarios del equipo docente, tutoría o coordinación.',
        variables: [],
      },
    ],
    createdForPhase: '7A',
    isBaseTemplate: true,
    isActive: true,
  },
  {
    code: 'final_memory_programme_level',
    name: 'Memoria final de ciclo y curso',
    description:
      'Plantilla base para la memoria final de un ciclo formativo y un curso concreto, con resultados académicos, evolución, incidencias y propuestas de mejora.',
    category: 'final_memory',
    scope: ['academic_year', 'programme', 'level'],
    outputFormats: ['docx', 'pdf'],
    requiredPermission: 'evaluations.statistics.view',
    requiredInputs: [
      {
        key: 'academicYearId',
        label: 'Curso académico',
        required: true,
        description: 'Selecciona el curso académico.',
      },
      {
        key: 'vocationalProgrammeId',
        label: 'Ciclo formativo',
        required: true,
        description: 'Selecciona el ciclo formativo, por ejemplo DAW o DAM.',
      },
      {
        key: 'academicLevelId',
        label: 'Curso / nivel',
        required: true,
        description: 'Selecciona el curso o nivel, por ejemplo primero o segundo.',
      },
    ],
    variables: [
      {
        key: 'academicYear.name',
        label: 'Curso académico',
        type: 'string',
        required: true,
        description: 'Nombre del curso académico.',
        example: '2026/2027',
      },
      {
        key: 'programme.name',
        label: 'Ciclo formativo',
        type: 'string',
        required: true,
        description: 'Nombre del ciclo formativo.',
        example: 'Desarrollo de Aplicaciones Web',
      },
      {
        key: 'level.name',
        label: 'Curso / nivel',
        type: 'string',
        required: true,
        description: 'Curso académico dentro del ciclo formativo.',
        example: '2º',
      },
      {
        key: 'stats.enrolled',
        label: 'Alumnado matriculado',
        type: 'number',
        required: true,
        description: 'Número total de alumnos matriculados.',
      },
      {
        key: 'stats.averageGrade',
        label: 'Nota media',
        type: 'number',
        required: false,
        description: 'Nota media calculada solo con calificaciones numéricas.',
      },
      {
        key: 'incidents.summary',
        label: 'Resumen de incidencias',
        type: 'object',
        required: false,
        description: 'Resumen de incidencias académicas registradas durante el curso.',
      },
      {
        key: 'improvementProposals',
        label: 'Propuestas de mejora',
        type: 'array',
        required: false,
        description: 'Listado de propuestas de mejora redactadas por el equipo docente.',
      },
    ],
    sections: [
      {
        key: 'cover',
        title: 'Portada',
        order: 1,
        required: true,
        description: 'Identificación del curso académico, ciclo formativo y curso o nivel.',
        variables: ['academicYear.name', 'programme.name', 'level.name'],
      },
      {
        key: 'academic_results',
        title: 'Resultados académicos',
        order: 2,
        required: true,
        description: 'Resumen de resultados globales.',
        variables: ['stats.enrolled', 'stats.averageGrade'],
      },
      {
        key: 'incidents',
        title: 'Incidencias académicas',
        order: 3,
        required: false,
        description: 'Análisis de incidencias académicas registradas.',
        variables: ['incidents.summary'],
      },
      {
        key: 'improvement',
        title: 'Propuestas de mejora',
        order: 4,
        required: false,
        description: 'Conclusiones y propuestas para el siguiente curso.',
        variables: ['improvementProposals'],
      },
    ],
    createdForPhase: '7A',
    isBaseTemplate: true,
    isActive: true,
  },
  {
    code: 'student_academic_record',
    name: 'Informe individual del alumno',
    description:
      'Plantilla base para el expediente individual de un alumno con matrícula, calificaciones, incidencias y formación en empresa.',
    category: 'student',
    scope: ['academic_year', 'student'],
    outputFormats: ['docx', 'pdf'],
    requiredPermission: 'evaluations.statistics.view',
    requiredInputs: [
      {
        key: 'studentId',
        label: 'Alumno',
        required: true,
        description: 'Selecciona el alumno.',
      },
    ],
    variables: [
      {
        key: 'student.fullName',
        label: 'Nombre completo',
        type: 'string',
        required: true,
        description: 'Nombre completo del alumno.',
      },
      {
        key: 'enrolments',
        label: 'Matrículas',
        type: 'array',
        required: true,
        description: 'Listado de matrículas del alumno.',
      },
      {
        key: 'grades',
        label: 'Calificaciones',
        type: 'array',
        required: false,
        description: 'Listado de calificaciones y estados.',
      },
      {
        key: 'incidents',
        label: 'Incidencias',
        type: 'array',
        required: false,
        description: 'Incidencias académicas asociadas al alumno.',
      },
      {
        key: 'workPlacements',
        label: 'Formación en empresa',
        type: 'array',
        required: false,
        description: 'Estancias de formación en empresa asociadas al alumno.',
      },
    ],
    sections: [
      {
        key: 'student_data',
        title: 'Datos del alumno',
        order: 1,
        required: true,
        description: 'Identificación académica del alumno.',
        variables: ['student.fullName'],
      },
      {
        key: 'enrolments',
        title: 'Matrículas',
        order: 2,
        required: true,
        description: 'Historial de matrículas.',
        variables: ['enrolments'],
      },
      {
        key: 'grades',
        title: 'Calificaciones',
        order: 3,
        required: false,
        description: 'Resultados académicos y estados no numéricos.',
        variables: ['grades'],
      },
      {
        key: 'incidents',
        title: 'Incidencias',
        order: 4,
        required: false,
        description: 'Incidencias académicas asociadas al alumno.',
        variables: ['incidents'],
      },
    ],
    createdForPhase: '7A',
    isBaseTemplate: true,
    isActive: true,
  },
  {
    code: 'work_placement_memory',
    name: 'Memoria de formación en empresa',
    description:
      'Plantilla base para documentar estancias de formación en empresa, seguimientos, incidencias, horas, actividades y evaluación final.',
    category: 'work_placement',
    scope: ['academic_year', 'programme', 'student', 'company', 'work_placement'],
    outputFormats: ['docx', 'pdf', 'xlsx'],
    requiredPermission: 'evaluations.statistics.view',
    requiredInputs: [
      {
        key: 'academicYearId',
        label: 'Curso académico',
        required: true,
        description: 'Selecciona el curso académico.',
      },
    ],
    variables: [
      {
        key: 'workPlacement.totalStudents',
        label: 'Alumnos en empresa',
        type: 'number',
        required: true,
        description: 'Número de alumnos con estancia registrada.',
      },
      {
        key: 'workPlacement.totalHours',
        label: 'Horas totales',
        type: 'number',
        required: false,
        description: 'Suma de horas previstas o realizadas.',
      },
      {
        key: 'workPlacement.pendingDocuments',
        label: 'Documentación pendiente',
        type: 'array',
        required: false,
        description: 'Listado de documentos pendientes.',
      },
      {
        key: 'workPlacement.followUps',
        label: 'Seguimientos',
        type: 'array',
        required: false,
        description: 'Visitas, llamadas o controles de seguimiento.',
      },
      {
        key: 'workPlacement.finalAssessment',
        label: 'Evaluación final',
        type: 'object',
        required: false,
        description: 'Resultado final de la formación en empresa.',
      },
    ],
    sections: [
      {
        key: 'summary',
        title: 'Resumen general',
        order: 1,
        required: true,
        description: 'Estado general de la formación en empresa.',
        variables: ['workPlacement.totalStudents', 'workPlacement.totalHours'],
      },
      {
        key: 'followups',
        title: 'Seguimientos',
        order: 2,
        required: false,
        description: 'Registro de visitas, contactos y observaciones.',
        variables: ['workPlacement.followUps'],
      },
      {
        key: 'documents',
        title: 'Documentación pendiente',
        order: 3,
        required: false,
        description: 'Control documental de la estancia.',
        variables: ['workPlacement.pendingDocuments'],
      },
      {
        key: 'assessment',
        title: 'Evaluación final',
        order: 4,
        required: false,
        description: 'Valoración final de la estancia.',
        variables: ['workPlacement.finalAssessment'],
      },
    ],
    createdForPhase: '7A',
    isBaseTemplate: true,
    isActive: true,
  },
];
