CREATE TABLE `students` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `student_code` VARCHAR(50) NULL,
    `first_name` VARCHAR(100) NOT NULL,
    `last_name_1` VARCHAR(100) NOT NULL,
    `last_name_2` VARCHAR(100) NULL,
    `document_type` ENUM('DNI', 'NIE', 'PASSPORT', 'OTHER') NULL,
    `document_number` VARCHAR(30) NULL,
    `email` VARCHAR(191) NULL,
    `phone` VARCHAR(30) NULL,
    `birth_date` DATE NULL,
    `address` VARCHAR(255) NULL,
    `postal_code` VARCHAR(10) NULL,
    `city` VARCHAR(100) NULL,
    `province` VARCHAR(100) NULL,
    `emergency_contact_name` VARCHAR(150) NULL,
    `emergency_contact_phone` VARCHAR(30) NULL,
    `notes` TEXT NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` DATETIME(0) NOT NULL,
    `deleted_at` DATETIME(0) NULL,

    UNIQUE INDEX `students_student_code_key`(`student_code`),
    UNIQUE INDEX `students_document_number_key`(`document_number`),
    INDEX `students_first_name_idx`(`first_name`),
    INDEX `students_last_name_1_last_name_2_idx`(`last_name_1`, `last_name_2`),
    INDEX `students_email_idx`(`email`),
    INDEX `students_city_idx`(`city`),
    INDEX `students_province_idx`(`province`),
    INDEX `students_is_active_idx`(`is_active`),
    INDEX `students_deleted_at_idx`(`deleted_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
